CREATE TABLE country (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) not null
);

CREATE TABLE city (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) not null,
                         population BIGINT,
                         country_id BIGINT,
                         CONSTRAINT FK_CITY_TO_COUNTRY
                             FOREIGN KEY (country_id) REFERENCES country(id)
);